server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # Agregamos este bloque para mapear la ruta limpia personalizada
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true