server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Activa el enrutamiento dinámico automático con Eureka
          lower-case-service-id: true # Permite usar nombres en minúsculas para las rutas

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true